### ISSUE TITLE
issue: addition of cancel button and alert time field

### ISSUE THREAD

**Issue by creative2113** [creative2113/nuxt-todo-app#1]
Hello, there!
I wanna to add cancel button.
and I need to add alert time for alarm.
please solve this problem.

**Comment by creative2115** [comment]
Hello, there.
I can update this project for this problem.
please hire me.
regards.

**Comment by creative2113** [comment]
ok.
please update that and create pull request.
have a good development.

**Comment by creative2115** [comment]
good.
I will start to work.
thank you.

**Comment by creative2115** [comment]
excuse me, can you give me the authority can merge myself on this branch.
thanks.

**Comment by creative2113** [comment]
I see.
Just a min.

**Comment by creative2113** [comment]
just done.
are you ok?

**Comment by creative2115** [comment]
okay
thank you

**Comment by creative2115** [comment]
Hello, I can handle this problem perfectly.

**Comment by creative2113** [comment]
good

**Comment by creative2113** [comment]
hello @creative2115 

how can do you handle this problem?
please tell me a little about the process.

**Comment by creative2115** [comment]
there are processes below.
 - addition cancel button
 - addition time field
 - addition backend for these problems
how about you?

**Comment by creative2113** [comment]
perfect!

**Comment by creative2113** [comment]
> there are processes below.
> 
> * addition cancel button
> * addition time field
> * addition backend for these problems
>   how about you?

very good!

**Comment by creative2113** [comment]
this issue was resolved and completed by creative2115

**Comment by creative2115** [comment]
thanks

**Comment by creative2113** [comment]
can you tell me about mark down issue problem?

**Comment by creative2115** [comment]
please wait for me.
I will just update that.
